enum CabinetStatus {
  AVAILABLE = "AVAILABLE",
  SET_EXPIRE_FULL = "SET_EXPIRE_FULL",
  SET_EXPIRE_AVAILABLE = "SET_EXPIRE_AVAILABLE",
  EXPIRED = "EXPIRED",
  BROKEN = "BROKEN",
  BANNED = "BANNED",
}

export default CabinetStatus;
