enum CabinetStatus {
  AVAILABLE = "AVAILABLE",
  FULL = "FULL",
  LIMITED_AVAILABLE = "LIMITED_AVAILABLE",
  OVERDUE = "OVERDUE",
  BROKEN = "BROKEN",
  BANNED = "BANNED",
  OVERDUE_PENALTY = "OVERDUE_PENALTY",
}

export default CabinetStatus;
