enum CabinetStatus {
  AVAILABLE = "AVAILABLE",
  FULL = "FULL",
  LIMITED_AVAILABLE = "LIMITED_AVAILABLE",
  OVERDUE = "OVERDUE",
  BROKEN = "BROKEN",
  BANNED = "BANNED",
  IN_SESSION = "IN_SESSION",
  PENDING = "PENDING",
}

export default CabinetStatus;
